---
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--all, --, --check]
      - id: clippy
        # args: [--all-targets, --, -D, warnings]
        args: [--all-targets]

  # NOTE (@NickLarsenNZ): v1.35.1 is broken.
  # See: https://github.com/adrienverge/yamllint/issues/678
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.0
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: [--severity=info]

  - repo: local
    hooks:
      - id: cargo-test
        name: cargo-test
        language: system
        entry: cargo test
        stages: [commit, merge-commit, manual]
        pass_filenames: false
