[package]
name = "crumpet"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive", "env"] }
clap_complete = "4.4.10"
snafu = "0.8.0"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
