---
name: Publish Docs
on:
  push:
    branches:
      - main
    paths:
      - "mkdocs.yml"
      - "docs/**"

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11.6'
          cache: 'pip'
      - run: pip install -r requirement.txt
      - run: mkdocs build --clean

  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO"