---
name: Publish Docs
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push-docs.yaml"
      - "mkdocs.yml"
      - "docs/**"

jobs:
  publish-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11.6'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build Docs
        run: mkdocs build --clean

      - name: Check GitHub Pages Status
        uses: crazy-max/ghaction-github-status@df4d23a4977438215339cf0fafceda8d9af8a0e5 #v4.0.0
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@c05ee637ec73429400a359430db8e5629f3f2564 #v4.0.0
        with:
          target_branch: gh-pages
          build_dir: .docs-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
